create table tb_client (id int8 generated by default as identity, name varchar(255), primary key (id));
INSERT INTO tb_client (name, cpf, income, birt_Date, children) VALUES ('Alex');
INSERT INTO tb_client (name, cpf, income, birt_Date, children) VALUES ('Maria');
INSERT INTO tb_client (name, cpf, income, birt_Date, children) VALUES ('Paulo');
INSERT INTO tb_client (name, cpf, income, birt_Date, children) VALUES ('Tomas');
INSERT INTO tb_client (name, cpf, income, birt_Date, children) VALUES ('Ana');
INSERT INTO tb_client (name, cpf, income, birt_Date, children) VALUES ('Marcos');